[Time]
$SlowTime_on1 = @APPLYSPELL|0X86C|For Honor in Skyrim.esp
$SlowTime_on1 = ![0.5]@UNAPPLYSPELL|0X86C|For Honor in Skyrim.esp
$SlowTime_off1 = @UNAPPLYSPELL|0X86C|For Honor in Skyrim.esp

$SlowTimeF_on1 = @APPLYSPELL|0X86D|For Honor in Skyrim.esp
$SlowTimeF_on1 = ![0.5]@UNAPPLYSPELL|0X86D|For Honor in Skyrim.esp
$SlowTimeF_off1 = @UNAPPLYSPELL|0X86D|For Honor in Skyrim.esp


[Layer]
$Layer_2 = @APPLYSPELL|0X826|For Honor in Skyrim.esp
$Layer_2 = ![0.36]@UNAPPLYSPELL|0X826|For Honor in Skyrim.esp


$Followup = @CAST|0X803|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0


[Dust]
$FMelee_Dust = @CAST|0X825|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
## 0.1 seconds faster than Hitframe 

$FMelee_GDust = @APPLYSPELL|0X868|For Honor in Skyrim.esp
$FMelee_GDust = ![3.0]@UNAPPLYSPELL|0X868|For Honor in Skyrim.esp

$FMelee_GDust2 = @APPLYSPELL|0X86A|For Honor in Skyrim.esp
$FMelee_GDust2 = ![3.0]@UNAPPLYSPELL|0X86A|For Honor in Skyrim.esp

[Dodge]
$FH_Dodge1 = @SETGHOST|1
$FH_Dodge1 = ![0.3]@SETGHOST|0
$FH_Iframe = @SETGHOST|1
$FH_Iframe = ![1.5]@SETGHOST|0



[Hit Sound]
$Shield_Hit = @CAST|0X82C|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$Fist_Hit = @CAST|0X82D|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
## Same as Hitframe 


[Ragdoll]
$FH_Ragdoll = @CAST|0X807|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0

[Taunt]
$Taunt_Smooth = @CAST|0X831|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0

[Effect]
$FHFX = @CAST|0X828|For Honor in Skyrim.esp|1|0|0|0|0|0|0|0|0

$FHFX_Body = @CAST|0X829|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$FHFX_Foot_R = @CAST|0X829|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$FHFX_Foot_L = @CAST|0X829|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$FHFX_LHand = @CAST|0X829|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0

$FHFX_Shield = @APPLYSPELL|0X82B|For Honor in Skyrim.esp
$FHFX_Shield = ![0.8]@UNAPPLYSPELL|0X82B|For Honor in Skyrim.esp


$h2h_Power = @CAST|0X86B|For Honor in Skyrim.esp|1|1|0|0|0|0|30|0|0


[Stagger]

$HitDown = @CAST|0X835|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitDown_Trigger = @CAST|0X870|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitUP = @CAST|0X833|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitUP_Trigger = @CAST|0X86F|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitLeft = @CAST|0X837|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitLeft_Trigger = @CAST|0X871|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitRight = @CAST|0X839|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitRight_Trigger = @CAST|0X872|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitStabIn = @CAST|0X83B|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitStabOut = @CAST|0X83D|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitStabOut_Trigger = @CAST|0X874|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitPush = @CAST|0X83F|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitPush_Trigger = @CAST|0X875|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitPushX2 = @CAST|0X841|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitPushX2_Trigger = @CAST|0X876|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitPushX3 = @CAST|0X84E|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$HitPushX3_Trigger = @CAST|0X877|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$ShieldPush = @CAST|0X875|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$ShieldPushX2 = @CAST|0X876|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$KnockDown = @CAST|0X820|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$KnockDown_Trigger = @CAST|0X827|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0

$FootStamp = @CAST|0X852|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$FootStamp_Trigger = @CAST|0X878|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$BodyStamp = @CAST|0X864|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$BodyStamp_Trigger = @CAST|0X879|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$Shield Flip = @CAST|0X832|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$Shield Flip_Trigger = @CAST|0X86E|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0

$Parry_Stagger = @CAST|0X809|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0
$Parry_Stagger_Trigger  = @CAST|0X82F|For Honor in Skyrim.esp|1|1|0|0|0|0|0|0|0


